mail.protocol=smtp
mail.host=slnxsagamail01.ptx.fr.sopra
mail.port=25
mail.smtp.auth=false
mail.smtp.starttls.enable=true
mail.from=saga@aviation-civile.fr
mail.username=root
mail.password=sopra123
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.ssl.trust=
mail.debug=false

########################################################################
#
# Contact DGAC
#
########################################################################
saga.dgac.adresse.mail=rick@dgac.fr

saga.mail.lien.demande=http://localhost:8080/demandes/demande/